"""Replace invented Stitch Framer visuals with the observed public page media.

framer-stitch.html remains the unchanged native Stitch export. The generated
framer.html is a source-backed draft for later visual/responsive review.
"""

import html
import json
import re
from pathlib import Path
from string import Template


ROOT = Path(__file__).resolve().parent
raw = (ROOT / "framer-stitch.html").read_text()
for phrase in ("Framer is the design agent for", "Lighthouse 100/100", "All systems normal"):
    assert phrase in raw, f"Unexpected native Stitch source: {phrase}"
ref = json.loads((ROOT / "framer-browser-reference.json").read_text())
manifest = json.loads((ROOT / "framer-asset-provenance.json").read_text())
assert ref["hero"]["heading"] == "Framer is the design agent for every step from idea to launch"
for name in manifest:
    assert (ROOT / "framer-assets" / name).is_file(), name


def esc(value):
    return html.escape(value, quote=True)


def asset(filename):
    assert filename in manifest, filename
    return f"framer-assets/{filename}"


mark = re.search(r'(<svg class="w-4 h-6[^>]+>.*?</svg>)', raw, re.S)
assert mark, "Native Stitch Framer mark missing"
mark = mark.group(1)

explorations = [
    ("Exploration", "exploration-haus.jpg"),
    ("Exploration — Big Intro", "exploration-big-intro.jpg"),
    ("Exploration — Side Nav", "exploration-side-nav.jpg"),
]
exploration_html = "".join(
    f'<div class="exploration"><span>{esc(label)}</span><img src="{asset(filename)}" alt="{esc(label)} website preview" loading="lazy"></div>'
    for label, filename in explorations
)
wheel_html = "".join(
    f'<img src="{asset("code-wheel-" + str(n) + ".jpg")}" alt="Framer code component visual" loading="lazy">'
    for n in range(1, 5)
)
showcase_html = "".join(
    f'<img src="{asset(filename)}" alt="{esc(label)} built with Framer" loading="lazy">'
    for label, filename in [
        ("Featured site", "showcase-main.png"),
        ("Maggie site", "showcase-maggie.png"),
        ("Midlife Engineering site", "showcase-midlife.png"),
    ]
)
customers = "".join(f"<span>{esc(name)}</span>" for name in ref["customerNames"])

footer_groups = [
    ("Product", [("AI", "https://www.framer.com/ai/"), ("Agents", "https://www.framer.com/agents/"), ("External Agents", "https://www.framer.com/agents/external/"), ("Design", "https://www.framer.com/design/"), ("Collaborate", "https://www.framer.com/collaborate/"), ("CMS", "https://www.framer.com/cms/"), ("Hosting", "https://www.framer.com/hosting/"), ("Performance", "https://www.framer.com/performance/"), ("SEO", "https://www.framer.com/seo/"), ("Skills", "https://www.framer.com/skills"), ("Convert", "https://www.framer.com/convert/"), ("Publish", "https://www.framer.com/publish/"), ("Updates", "https://www.framer.com/updates")]),
    ("Marketplace", [("Templates", "https://www.framer.com/community/"), ("Components", "https://www.framer.com/community/"), ("Plugins", "https://www.framer.com/community/"), ("Gallery", "https://www.framer.com/community/")]),
    ("Business", [("Switch", "https://www.framer.com/switch/"), ("Enterprise", "https://www.framer.com/enterprise/"), ("Agencies", "https://www.framer.com/agencies/"), ("Startups", "https://www.framer.com/startups/"), ("Pricing", "https://www.framer.com/pricing")]),
    ("Resources", [("Academy", "https://www.framer.com/academy/"), ("Developers", "https://www.framer.com/developers/"), ("Guides", "https://www.framer.com/guides"), ("Blog", "https://www.framer.com/blog/"), ("Stories", "https://www.framer.com/stories/"), ("Help Articles", "https://www.framer.com/help/"), ("Contact", "https://www.framer.com/contact/")]),
    ("Solutions", [("Designers", "https://www.framer.com/solutions/"), ("Marketers", "https://www.framer.com/solutions/"), ("Builders", "https://www.framer.com/solutions/"), ("Website builder", "https://www.framer.com/solutions/")]),
    ("Company", [("Careers", "https://www.framer.com/careers/"), ("Brand", "https://www.framer.com/brand"), ("Legal", "https://www.framer.com/legal/")]),
    ("By Framer", [("Merch", "https://www.framer.com/store"), ("Keyboard", "https://www.framer.com/f1"), ("Stack Score", "https://www.framer.com/stack-score"), ("Free domains", "https://www.framer.com/domains/"), ("AEO scanner", "https://www.framer.com/aeo")]),
]
footer_html = "".join(
    f'<div class="footer-group"><h3>{esc(title)}</h3>'
    + "".join(f'<a href="{esc(url)}">{esc(label)}</a>' for label, url in links)
    + "</div>"
    for title, links in footer_groups
)

page = Template(r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>$title</title>
<meta name="description" content="Framer is the design agent for every step from idea to launch.">
<style>
@font-face{font-family:Walsheim;src:url(framer-assets/font-medium.woff2) format("woff2");font-weight:500;font-display:swap}
@font-face{font-family:Walsheim;src:url(framer-assets/font-bold.woff2) format("woff2");font-weight:700;font-display:swap}
:root{font-family:Walsheim,Arial,sans-serif;background:#000;color:#fff}*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#000;color:#fff}a{color:inherit;text-decoration:none}button,input{font:inherit}button{cursor:pointer}img{display:block;max-width:100%}h1,h2,h3,p,blockquote{margin:0}
.site-header{height:64px;background:#000;position:sticky;top:0;z-index:50;padding:0 40px;display:flex;align-items:center;justify-content:space-between}.nav-left,.nav-links,.nav-right,.brand{display:flex;align-items:center}.brand{gap:9px;font-size:15px;font-weight:700}.brand svg{height:24px;width:16px}.nav-left{gap:29px}.nav-links{gap:28px;font-size:15px;font-weight:500}.nav-links a:hover,.nav-right a:first-child:hover{color:#aaa}.nav-right{gap:17px;font-size:14px}.nav-right a:first-child{color:#aaa}.signup{background:#fff;color:#111;border-radius:8px;padding:9px 12px}
.fixed-width{max-width:1280px;margin:auto}.hero{height:1337px;position:relative}.hero h1{position:absolute;left:40px;top:100px;width:760px;font-size:54px;font-weight:500;line-height:1;letter-spacing:-.038em}.hero-actions{position:absolute;left:40px;right:40px;top:233px;display:flex;align-items:center;gap:10px;font-size:14px}.hero-actions a{padding:9px 15px;border-radius:8px}.hero-actions .primary{background:#fff;color:#111}.hero-actions .secondary{background:#202020;color:#fff}.hero-actions .skills{margin-left:auto;color:#aaa;padding:0}.hero-video{position:absolute;left:40px;top:308px;width:calc(100% - 80px);height:673px;border:1px solid #292929;border-radius:20px;overflow:hidden;background:#08080c;object-fit:cover}.customers-link{position:absolute;right:40px;bottom:77px;color:#aaa;font-size:15px}
.agents{height:3117px}.agents-heading{height:100px;display:flex;justify-content:space-between;align-items:start;padding:0 40px}.agents-heading h2{font-size:42px;line-height:1.15;letter-spacing:-.045em;max-width:520px}.agents-heading a{font-size:17px;align-self:center}.agent-row{height:700px;padding:0 40px;display:grid;grid-template-columns:minmax(0,928px) 260px;gap:12px}.agent-main{min-width:0}.agent-visual{height:520px;border:1px solid #252525;border-radius:20px;overflow:hidden;background:#111;position:relative}.agent-caption{padding:29px 27px 0}.agent-caption h3{font-size:20px;font-weight:500}.agent-caption p{font-size:18px;line-height:1.35;color:#999;max-width:520px;margin-top:5px}.agent-caption a{float:right;font-size:16px;margin-top:-22px}.agent-chat{height:615px;border:1px solid #252525;border-radius:20px;background:#171717;padding:10px;font-size:14px;color:#a9a9a9}.chat-bubble{border:1px solid #303030;border-radius:14px;padding:11px;line-height:1.25;color:#ddd}.chat-thinking{padding:17px 9px}.chat-compose{border:1px solid #2a2a2a;border-radius:13px;padding:14px;margin-top:260px;height:90px}.exploration-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:20px;padding:65px 65px 25px}.exploration{min-width:0}.exploration span{display:block;color:#aaa;font-size:13px;margin-bottom:8px}.exploration img{width:100%;height:340px;object-fit:cover;object-position:top;border:1px solid #3b5368}.cms-ui{width:calc(100% - 110px);margin:52px auto 0;height:420px;background:#121212;border:1px solid #2a2a2a;border-radius:10px;display:grid;grid-template-columns:220px 1fr;overflow:hidden}.cms-side{border-right:1px solid #292929;padding:20px;color:#bbb;font-size:14px}.cms-side strong,.cms-side span{display:block;margin-bottom:14px}.cms-side .selected{background:#292929;border-radius:7px;padding:10px}.cms-table{padding:20px;font-size:14px;color:#aaa}.cms-table .table-top{color:#eee;padding-bottom:18px;border-bottom:1px solid #292929}.cms-table .table-row{padding:16px 0;border-bottom:1px solid #282828;display:flex;justify-content:space-between;gap:20px}.cms-table .status{color:#86a894}.code-wheel{display:flex;align-items:center;justify-content:center;gap:22px;height:100%;background:radial-gradient(circle,#242424 0%,#0c0c0c 70%)}.code-wheel img{width:170px;height:170px;object-fit:cover;border-radius:14px;transform:rotate(-7deg)}.code-wheel img:nth-child(even){transform:translateY(55px) rotate(7deg)}.external-visual{padding:25px}.external-visual img{width:100%;height:400px;object-fit:cover;border-radius:10px}.external-tags{display:flex;gap:12px;color:#aaa;font-size:15px;padding:13px}
.platform{height:1817px;padding:0 40px}.platform h2{font-size:42px;line-height:1.15;letter-spacing:-.045em;width:320px}.bento{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:66px}.bento-card{height:430px;border-radius:18px;border:1px solid #292929;background:#151515;padding:24px;overflow:hidden;position:relative}.bento-card h3{font-size:20px;font-weight:500;position:absolute;left:24px;bottom:24px}.bento-card .inner{height:340px;color:#aaa;font-size:13px}.bento-card strong{color:#eee}.vitals{display:flex;gap:12px;margin-top:30px}.vitals span{border:1px solid #333;padding:14px;border-radius:8px;font-size:16px}.vitals b{display:block;color:#fff;font-size:30px;font-weight:500}.bento-card .big{font-size:82px;line-height:1;color:#fff}.bento-card .list span{display:block;padding:9px;border-bottom:1px solid #333}.analytics-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:15px;margin-top:20px}.analytics-grid span{display:block}.analytics-grid b{display:block;color:#fff;font-size:30px;font-weight:500}
.showcase{height:1238px;padding:0 40px;overflow:hidden}.showcase h2,.trust h2,.community h2{font-size:42px;line-height:1.15;letter-spacing:-.045em}.section-top{display:flex;align-items:end;justify-content:space-between}.section-top a{font-size:16px}.showcase-track{display:flex;gap:10px;margin-top:45px;width:max-content;position:relative;left:-10px}.showcase-track img{height:450px;width:auto;object-fit:cover;border-radius:8px}.trust{height:819px;padding:0 40px}.trust h2{max-width:365px}.customer-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:17px;margin-top:70px}.customer-grid span{height:130px;border:1px solid #292929;border-radius:12px;display:grid;place-items:center;font-size:26px;font-weight:700}.community{height:1217px;padding:0 40px}.community h2{max-width:550px}.community-panel{display:grid;grid-template-columns:2fr 1fr;gap:15px;margin-top:60px}.community-feed,.community-side{height:570px;border-radius:18px;border:1px solid #2b2b2b;background:#151515;padding:25px}.feed-header{font-size:22px;margin-bottom:28px}.feed-card{border-bottom:1px solid #2b2b2b;padding:16px 0;font-size:16px;color:#ccc}.feed-card strong{display:block;color:#fff;margin-bottom:5px}.community-side h3{font-size:21px}.community-side p{margin-top:22px;color:#aaa}
.end-cta{text-align:center;min-height:560px;padding-top:0}.end-cta h2{font-size:54px;letter-spacing:-.045em}.prompt-box{margin:34px auto 0;border:1px solid #343434;background:#171717;border-radius:16px;width:min(680px,calc(100% - 40px));height:150px;padding:22px;text-align:left;color:#888}.prompt-box input{border:0;background:none;outline:none;color:#fff;width:100%;font-size:17px}.suggestions{display:flex;justify-content:center;gap:14px;margin-top:20px}.suggestions button{border:1px solid #333;background:#191919;color:#aaa;border-radius:7px;padding:10px 13px}.start-no-ai{display:inline-block;margin-top:30px;color:#aaa}
.site-footer{border-top:1px solid #242424;padding:70px 40px 35px}.footer-grid{display:grid;grid-template-columns:repeat(7,1fr);gap:24px}.footer-group{display:flex;flex-direction:column;gap:13px;font-size:14px}.footer-group h3{font-size:16px;margin-bottom:8px}.footer-group a{color:#aaa}.footer-group a:hover{color:#fff}.footer-bottom{margin-top:100px;display:flex;justify-content:space-between;color:#888;font-size:14px}.cookie-box{position:fixed;z-index:80;bottom:20px;left:20px;width:340px;background:#fff;color:#111;border-radius:16px;padding:18px 20px;font-size:14px;line-height:1.45;box-shadow:0 8px 24px #0005;display:flex;gap:15px}.cookie-box button{border:0;border-radius:8px;background:#e5e5e5;padding:9px 11px;align-self:center}
@media(max-width:900px){.site-header{padding:0 20px}.nav-links{gap:10px}.hero h1{left:20px;width:calc(100% - 40px);font-size:48px}.hero-actions{left:20px;right:20px}.hero-video{left:20px;width:calc(100% - 40px);height:auto;aspect-ratio:1200/673}.hero{height:1050px}.agents,.platform,.showcase,.trust,.community{height:auto;padding-bottom:90px}.agents-heading,.agent-row{padding-left:20px;padding-right:20px}.agent-row{grid-template-columns:minmax(0,1fr) 220px}.exploration-grid{padding:50px 20px 20px}.cms-ui{width:95%}.platform,.showcase,.trust,.community{padding-left:20px;padding-right:20px}.bento{grid-template-columns:repeat(2,1fr)}.footer-grid{grid-template-columns:repeat(4,1fr)}}
@media(max-width:620px){.nav-links{display:none}.site-header{height:60px}.hero{height:720px}.hero h1{top:80px;font-size:42px;line-height:1.05}.hero-actions{top:224px;flex-wrap:wrap}.hero-actions .skills{width:100%;margin:8px 0 0}.hero-video{top:330px}.customers-link{bottom:35px}.agents-heading{height:auto;display:block;padding-bottom:30px}.agents-heading h2{font-size:34px}.agents-heading a{display:inline-block;margin-top:16px}.agent-row{height:auto;display:block;margin-bottom:60px}.agent-visual{height:400px}.agent-chat{display:none}.agent-caption{padding:20px 5px 0}.agent-caption a{float:none;display:inline-block;margin-top:15px}.exploration-grid{gap:8px;padding:50px 10px 10px}.exploration img{height:240px}.exploration span{font-size:10px}.cms-ui{margin-top:25px;grid-template-columns:100px 1fr;height:340px}.cms-side{padding:10px;font-size:10px}.cms-table{padding:10px;font-size:10px}.code-wheel img{width:85px;height:85px}.external-visual img{height:260px}.platform h2,.showcase h2,.trust h2,.community h2{font-size:34px}.bento{grid-template-columns:1fr}.bento-card{height:300px}.showcase-track img{height:300px}.customer-grid{grid-template-columns:repeat(2,1fr)}.customer-grid span{height:90px;font-size:19px}.community-panel{grid-template-columns:1fr}.community-side{display:none}.end-cta h2{font-size:39px}.suggestions{flex-wrap:wrap;padding:0 20px}.footer-grid{grid-template-columns:repeat(2,1fr)}.cookie-box{width:calc(100% - 40px)}}
</style></head><body>
<header class="site-header"><div class="nav-left"><a class="brand" href="https://www.framer.com/" aria-label="Framer home">$mark <span>Framer</span></a><nav class="nav-links"><a href="#platform">Platform⌄</a><a href="https://www.framer.com/solutions/">Solutions⌄</a><a href="https://www.framer.com/academy/">Resources⌄</a><a href="https://www.framer.com/enterprise/">Enterprise</a><a href="https://www.framer.com/pricing">Pricing</a></nav></div><div class="nav-right"><a href="https://www.framer.com/r/login">Log in</a><a class="signup" href="https://www.framer.com/r/signup/">Sign up</a></div></header>
<main>
<section class="hero fixed-width"><h1>Framer is the design agent for<br>every step from idea to launch</h1><div class="hero-actions"><a class="primary" href="https://www.framer.com/r/signup/">Get started for free</a><a class="secondary" href="https://updates.framer.com/electron/darwin/arm64/Framer.zip">Download app ↓</a><a class="skills" href="https://www.framer.com/skills">New: Skills →</a></div><video class="hero-video" autoplay muted loop playsinline poster="$hero_poster" src="$hero_video" aria-label="Framer homepage product video"></video><a class="customers-link" href="https://www.framer.com/stories/">Meet our customers →</a></section>
<section class="agents fixed-width" id="platform"><div class="agents-heading"><h2>Agents that work alongside you, not instead of you</h2><a href="https://www.framer.com/agents/">Start with agents →</a></div>
<div class="agent-row"><div class="agent-main"><div class="agent-visual"><div class="exploration-grid">$explorations</div></div><div class="agent-caption"><h3>Design with an agent</h3><p>A professional design agent, native to the canvas. It works directly on your site to generate and refine in place, with every change visible, editable, and under your control.</p><a href="https://www.framer.com/agents/">Start with Agents →</a></div></div><div class="agent-chat"><div class="chat-bubble">Desktop&nbsp; Create a few layout variations of my site. Keep the content but try some different compositions.</div><div class="chat-thinking">Thinking...<br>Created a design plan</div><div class="chat-compose">Add follow up...</div></div></div>
<div class="agent-row"><div class="agent-main"><div class="agent-visual"><div class="cms-ui"><div class="cms-side"><strong>▣ CMS</strong><span>Collections</span><span>Academy</span><span>Blog</span><span class="selected">Articles&nbsp; 320</span><span>Creators&nbsp; 256</span><span>Categories&nbsp; 18</span><span>Styles&nbsp; 7</span></div><div class="cms-table"><div class="table-top">Site · main&nbsp;&nbsp;&nbsp;&nbsp; Title　 Image　 Category　 Status</div><div class="table-row"><span>Designing calmer interfaces inspired by nature</span><span class="status">Live</span></div><div class="table-row"><span>Organic shapes and natural motion in modern UI</span><span class="status">Live</span></div><div class="table-row"><span>Earthy color palettes inspired by the natural world</span><span class="status">Live</span></div><div class="table-row"><span>Designing with growth: how nature shapes UX patterns</span><span class="status">Live</span></div></div></div></div><div class="agent-caption"><h3>Run your CMS with an agent</h3><p>Manage more. Publish faster. The CMS agent sets up, organizes, and updates your entire CMS, connecting it directly to the canvas so content and design stay in sync.</p><a href="https://www.framer.com/agents/">Start with Agents →</a></div></div><div class="agent-chat"><div class="chat-bubble">/cms&nbsp; Add these articles to my collection and list them on the articles page.</div><div class="chat-thinking">Thinking...</div><div class="chat-compose">Add follow up...</div></div></div>
<div class="agent-row"><div class="agent-main"><div class="agent-visual"><div class="code-wheel">$wheel</div></div><div class="agent-caption"><h3>Code with an agent</h3><p>Agents turn your wildest ideas into code and put them on your site. From simple custom effects to complex interactions.</p><a href="https://www.framer.com/agents/">Start with Agents →</a></div></div><div class="agent-chat"><div class="chat-bubble">ImageWheel</div><div class="chat-thinking">Framer code component</div><div class="chat-compose">Add follow up...</div></div></div>
<div class="agent-row"><div class="agent-main"><div class="agent-visual external-visual"><img src="$external" alt="Framer external AI product visual" loading="lazy"><div class="external-tags"><span>Claude</span><span>Cursor</span><span>Codex</span></div></div><div class="agent-caption"><h3>Connect to any AI</h3><p>Take action on your site from anywhere. Update copy from Slack. Trigger CMS changes from the terminal. Ship from a GitHub PR. Drive it all from your Terminal, Codex in ChatGPT, Claude Code, Cursor, or any external AI.</p><a href="https://www.framer.com/agents/external/">Install →</a></div></div><div class="agent-chat"><div class="chat-bubble">framer-agent</div><div class="chat-thinking">Claude Code · Cursor · Codex</div><div class="chat-compose">Copy install prompt</div></div></div></section>
<section class="platform fixed-width"><h2>Not just vibes, a full platform</h2><div class="bento"><a class="bento-card" href="https://www.framer.com/performance/"><div class="inner"><strong>Core Web Vitals　GOOD</strong><div class="vitals"><span>LCP<b>1.1s</b></span><span>INP<b>95ms</b></span><span>CLS<b>0.01</b></span></div></div><h3>Performance</h3></a><a class="bento-card" href="https://www.framer.com/cms/"><div class="inner"><strong>Collections</strong><div class="list"><span>Blog</span><span>Careers</span><span>Events</span><span>Categories</span><span>Speakers</span></div></div><h3>CMS</h3></a><a class="bento-card" href="https://www.framer.com/seo/"><div class="inner"><strong>Site Settings</strong><div class="list"><span>Title　Comet Browser: a Personal…</span><span>URL　/comet/</span><span>Page Description</span><span>Social Preview</span></div></div><h3>SEO</h3></a><a class="bento-card" href="https://www.framer.com/collaborate/"><div class="inner"><strong>Branches</strong><div class="list"><span>Main　1m</span><span>use-cases　1m</span><span>publishing　8m</span><span>content　10m</span></div></div><h3>Collaboration</h3></a><a class="bento-card" href="https://www.framer.com/academy/"><div class="inner"><strong>Locales</strong><div class="list"><span>NL　Dutch　35%</span><span>IT　Italian　100%</span><span>CN　Chinese　90%</span></div></div><h3>Localization</h3></a><a class="bento-card" href="https://www.framer.com/hosting/"><div class="inner"><div class="big">99.99%</div><strong>uptime</strong></div><h3>Hosting</h3></a><a class="bento-card" href="https://www.framer.com/legal/security/"><div class="inner"><strong>https://www.framer.com/</strong></div><h3>Security</h3></a><a class="bento-card" href="https://www.framer.com/analytics"><div class="inner"><strong>Analytics</strong><div class="analytics-grid"><span>Live Visitors<b>400</b></span><span>Unique Visitors<b>1.7M</b></span><span>Total Pageviews<b>2.2M</b></span><span>Bounce Rate<b>40.9%</b></span></div></div><h3>Analytics</h3></a><a class="bento-card" href="https://www.framer.com/analytics"><div class="inner"><strong>Home Page 2026　WINNER</strong><div class="analytics-grid"><span>Views<b>4,916</b></span><span>Conversion<b>17.1%</b></span></div></div><h3>A/B Testing</h3></a></div></section>
<section class="showcase fixed-width"><div class="section-top"><h2>Shipped with Framer</h2><a href="https://www.framer.com/community/">See Framer sites →</a></div><div class="showcase-track">$showcase</div></section>
<section class="trust fixed-width"><div class="section-top"><h2>Trusted by teams shipping big sites</h2><a href="https://www.framer.com/stories/">Read stories →</a></div><div class="customer-grid">$customers</div></section>
<section class="community fixed-width"><div class="section-top"><h2>Built on a community that isn’t going anywhere</h2><a href="https://www.framer.com/community/">Browse the community →</a></div><div class="community-panel"><div class="community-feed"><div class="feed-header">Community　 Feed　 Hype　 Experts　 Gallery</div><div class="feed-card"><strong>Lee Black</strong>The only Framer Liquid Glass component that is cross browser and mobile friendly.</div><div class="feed-card"><strong>Gustave Flowbert</strong>Billie · Template</div><div class="feed-card"><strong>Ben Fryc</strong>in my fisheye era</div><div class="feed-card"><strong>Renny Mathew</strong>Carousel 3D · Component</div></div><div class="community-side"><h3>Trending Templates</h3><p>Can this be built in Framer?</p><p>Recraft</p><p>Tidy Up</p><p>Hover Zoom</p><p>Lou</p></div></div></section>
<section class="end-cta fixed-width"><h2>Your next idea starts here</h2><div class="prompt-box"><input aria-label="Describe your website idea" placeholder="Describe your site…"><a class="signup" href="https://www.framer.com/signup">Start →</a></div><div class="suggestions"><button type="button">Create personal portfolio</button><button type="button">Build startup site</button><button type="button">Launch landing page</button><button type="button">Start company blog</button></div><a class="start-no-ai" href="https://www.framer.com/signup">Start without AI →</a></section>
</main><footer class="site-footer"><div class="footer-grid">$footer</div><div class="footer-bottom"><a class="brand" href="https://www.framer.com/">$mark <span>Framer</span></a><span>English　 ·　 Twitter / X　 ·　 YouTube　 ·　 Instagram　 ·　 LinkedIn</span></div></footer>
<div class="cookie-box" id="cookie-box"><span>We use cookies to enhance your experience, analyze site traffic and deliver personalized ads and content. Read our <a href="https://www.framer.com/legal/cookie-policy/">Cookie Policy</a>.</span><button type="button" onclick="document.getElementById('cookie-box').remove()">Ok</button></div>
</body></html>''').substitute(
    title=esc(ref["title"]), mark=mark,
    hero_poster=asset("hero-poster.jpg"), hero_video=asset("hero.mp4"),
    explorations=exploration_html, wheel=wheel_html,
    external=asset("external-main.jpg"), showcase=showcase_html,
    customers=customers, footer=footer_html,
)

for invented in (
    "Lighthouse 100/100", "Unlimited items", "All systems normal",
    "SaaS landing page", "Portfolio with 3D elements", "Relational Schema & Content Syncer",
):
    assert invented not in page, invented
(ROOT / "framer.html").write_text(page)
print("framer.html", len(page), "bytes")
