#!/usr/bin/env python3
"""Build a static IBM Canada study from dated official copy and observed media."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1] / '.stitch-work' / 'current-official'
IMAGES = json.loads((ROOT / 'ibm-browser-image-provenance.json').read_text())


def image(name: str) -> str:
    matches = [item for item in IMAGES if name in item['name']]
    if len(matches) != 1:
        raise ValueError(f'Expected one observed IBM image for {name}: {matches}')
    return 'ibm-browser-images/' + matches[0]['path']


def main() -> None:
    html = '''<!doctype html><html lang="en-CA"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>IBM Canada homepage study · Awesome AI Web Design</title>
<style>
@font-face{font-family:IBM Plex Sans;src:url(ibm-fonts/IBMPlexSans-Light.woff2) format('woff2');font-weight:300;font-display:swap}
@font-face{font-family:IBM Plex Sans;src:url(ibm-fonts/IBMPlexSans-Regular.woff2) format('woff2');font-weight:400;font-display:swap}
@font-face{font-family:IBM Plex Sans;src:url(ibm-fonts/IBMPlexSans-Medium.woff2) format('woff2');font-weight:500;font-display:swap}
@font-face{font-family:IBM Plex Sans;src:url(ibm-fonts/IBMPlexSans-SemiBold.woff2) format('woff2');font-weight:600;font-display:swap}
@font-face{font-family:IBM Plex Sans;src:url(ibm-fonts/IBMPlexSans-Italic.woff2) format('woff2');font-weight:400;font-style:italic;font-display:swap}
:root{--blue:#0f62fe;--ink:#161616;--gray:#525252;--rule:#e0e0e0;--field:#f4f4f4}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#fff;color:var(--ink);font-family:IBM Plex Sans,'Helvetica Neue',Arial,sans-serif;font-weight:400}button,input{font:inherit}a{color:inherit}button{cursor:pointer}
.header{height:49px;border-bottom:1px solid var(--rule);display:flex;align-items:center;background:white;position:sticky;top:0;z-index:100}
.brand{width:126px;height:48px;display:flex;align-items:center;padding-left:32px;border-right:1px solid var(--rule);text-decoration:none}
.ibm-mark{font-family:IBM Plex Sans,Arial,sans-serif;font-size:29px;font-weight:600;letter-spacing:-3px;line-height:1;display:inline-block;background:repeating-linear-gradient(to bottom,#161616 0 2px,transparent 2px 3.8px);color:transparent;background-clip:text;-webkit-background-clip:text}
.nav{height:100%;display:flex;align-items:center}.nav a{font-size:16px;color:#525252;text-decoration:none;padding:0 16px;height:100%;display:flex;align-items:center;gap:10px}.nav a:hover,.utility a:hover{background:var(--field)}
.chevron{width:9px;height:9px;border-right:1px solid currentColor;border-bottom:1px solid currentColor;transform:rotate(45deg);margin-top:-4px}
.utility{margin-left:auto;height:100%;display:flex}.utility a{display:grid;place-items:center;width:48px;height:48px;color:#525252;text-decoration:none}.utility svg,.mobile-menu-button svg{width:20px;height:20px;fill:none;stroke:currentColor;stroke-width:1.5;stroke-linecap:round;stroke-linejoin:round}
.mobile-menu-button{display:none;height:48px;width:48px;border:0;background:white;color:#525252}
.mobile-menu{display:none;position:fixed;z-index:99;top:49px;bottom:0;left:0;right:0;background:white;overflow:auto}.mobile-menu.open{display:block}.mobile-menu a,.mobile-menu button{width:100%;min-height:49px;padding:12px 16px;border:0;border-bottom:1px solid var(--rule);background:white;color:#525252;text-align:left;text-decoration:none;font-size:14px;display:flex;align-items:center;justify-content:space-between}.mobile-menu .back{color:var(--blue)}.mobile-menu strong{display:block;padding:16px;font-size:14px}.mobile-menu [hidden]{display:none!important}
.hero{padding:58px 16px 72px 32px;display:grid;grid-template-columns:minmax(360px,452px) minmax(400px,1fr) 156px;gap:16px;min-height:604px}
.hero-copy{display:flex;flex-direction:column;min-width:0}.hero h1{font-weight:300;font-size:48px;line-height:1.12;letter-spacing:-.5px;margin:0;max-width:440px;background:linear-gradient(100deg,#0f62fe 20%,#6841c2);background-clip:text;-webkit-background-clip:text;color:transparent}
.hero-description{margin:90px 24px 0 0;font-size:20px;line-height:1.4;max-width:425px}.hero-description em{font-style:italic}
.hero-actions{display:flex;gap:16px;margin-top:30px}.action{display:flex;align-items:center;justify-content:space-between;text-decoration:none;padding:0 16px;min-height:48px;font-size:16px;line-height:1.15;border:1px solid var(--blue);width:202px}.action.primary{background:var(--blue);color:#fff}.action.secondary{background:white;color:var(--blue)}.action span:last-child{font-size:24px;font-weight:300;line-height:1}
.hero-visual{width:100%;aspect-ratio:3/2;object-fit:cover;background:var(--field);align-self:start}.news{border-left:1px solid var(--rule);padding-left:16px}.news h2{font-size:15px;font-weight:600;margin:2px 0 46px}.news a{color:var(--blue);display:block;font-size:16px;line-height:1.45;text-decoration:none;padding:0 0 28px;margin-bottom:30px;border-bottom:1px solid var(--rule)}.news a span{display:block;margin-top:17px}.news-dots{display:flex;gap:18px;color:#c6c6c6;font-size:12px}.news-dots b{color:var(--blue);font-weight:400}
main section:not(.hero){padding-left:32px;padding-right:32px}.section-title{font-size:38px;font-weight:300;line-height:1.17;margin:0 0 30px}.eyebrow{font-size:16px;font-weight:600;margin:0 0 24px}
.recommend{padding-top:24px;padding-bottom:54px;border-top:1px solid var(--rule)}.recommend-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:16px}.recommend-card{min-height:225px;border:1px solid var(--rule);text-decoration:none;display:flex;flex-direction:column}.recommend-card img{width:100%;height:100px;object-fit:cover;background:var(--field)}.recommend-card .copy{padding:14px 16px;display:block}.recommend-card small{display:block;color:var(--gray);font-size:12px;margin-bottom:6px}.recommend-card strong{font-size:18px;line-height:1.25;font-weight:400}
.impact{padding-top:34px;padding-bottom:72px;border-top:1px solid var(--rule)}.impact-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px}.impact-card{border:1px solid #c6c6c6;text-decoration:none;min-height:378px;display:flex;flex-direction:column}.impact-card img{width:100%;height:105px;object-fit:contain;object-position:left center;padding:14px 16px}.impact-card .main{font-size:25px;line-height:1.25;padding:12px 16px;flex:1}.impact-card .metric{background:var(--field);padding:16px;min-height:95px;font-size:14px;color:var(--gray)}.impact-card .metric b{display:block;font-size:25px;color:var(--ink);font-weight:400}
.technology{padding-top:52px;padding-bottom:82px;border-top:1px solid var(--rule)}.technology>.intro{font-size:18px;line-height:1.5;max-width:930px;margin:-6px 0 32px}.technology-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px}.tech-card{background:var(--field);min-height:205px;display:flex;flex-direction:column;padding:20px 16px;text-decoration:none}.tech-card h3{font-size:23px;font-weight:400;margin:0}.tech-card p{font-size:15px;line-height:1.4;margin:24px 0 auto}.tech-card .arrow{align-self:flex-end;color:var(--blue);font-size:24px}
.inside{padding-top:56px;padding-bottom:70px;border-top:1px solid var(--rule)}.inside-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:32px}.inside h3{font-size:25px;font-weight:400;margin:0 0 15px}.inside p{font-size:16px;line-height:1.5;max-width:340px}.inside a{color:var(--blue);display:block;margin:10px 0;text-decoration:none}
.connected{border-top:1px solid var(--rule);padding-top:56px;padding-bottom:70px}.connected-grid{display:grid;grid-template-columns:1fr 1fr;gap:32px}.connected img{width:100%;aspect-ratio:16/9;object-fit:cover}.newsletter{background:var(--field);padding:30px}.newsletter h3{font-size:24px;font-weight:400;margin:0 0 12px}.newsletter p{font-size:15px;line-height:1.45}.newsletter label{display:block;font-size:13px;margin:15px 0}.newsletter input{height:42px;border:0;border-bottom:1px solid #8d8d8d;background:#fff;padding:8px;width:100%}.newsletter button{border:0;background:var(--blue);color:white;padding:14px 26px;margin-top:12px}
.footer{border-top:1px solid var(--rule);padding:48px 32px 25px}.footer-top{display:grid;grid-template-columns:repeat(4,1fr);gap:24px}.footer h3{font-size:16px;font-weight:600;margin:0 0 18px}.footer a{display:block;color:#525252;text-decoration:none;margin:0 0 12px;font-size:14px}.footer-bottom{border-top:1px solid var(--rule);padding-top:23px;margin-top:35px;display:flex;gap:28px;font-size:12px;color:#525252}.footer-bottom a{font-size:12px}
@media(max-width:900px){.header{height:49px}.brand{width:auto;border:0;padding-left:16px}.ibm-mark{font-size:24px}.nav{display:none}.mobile-menu-button{display:grid;place-items:center}.utility a{width:48px}.utility .contact{display:none}.hero{display:block;padding:35px 16px 30px;min-height:0}.hero h1{font-size:33px;line-height:1.22;max-width:350px}.hero-description{font-size:20px;line-height:1.4;margin:56px 0 0;max-width:none}.hero-actions{display:flex;flex-direction:column;gap:16px;margin-top:30px}.action{width:min(100%,288px);min-height:48px}.hero-visual{margin-top:32px;display:block;width:100%}.news{border-left:0;border-top:1px solid var(--rule);padding:22px 0 0;margin-top:35px}.news h2{margin-bottom:22px}.news a{font-size:15px;margin-bottom:12px;padding-bottom:15px}.news-dots{display:none}main section:not(.hero){padding-left:16px;padding-right:16px}.section-title{font-size:31px}.recommend{padding-top:28px;padding-bottom:38px}.recommend-grid{grid-template-columns:1fr;gap:16px}.recommend-card{min-height:135px;flex-direction:row}.recommend-card img{height:auto;width:108px;object-fit:cover}.recommend-card .copy{padding:14px;align-self:center}.recommend-card strong{font-size:16px}.impact{padding-top:42px;padding-bottom:40px}.impact-grid{grid-template-columns:1fr}.impact-card{min-height:340px}.impact-card img{height:85px}.impact-card .main{font-size:28px}.impact-card .metric{min-height:86px}.technology{padding-top:42px;padding-bottom:48px}.technology-grid{grid-template-columns:1fr 1fr}.tech-card{min-height:180px}.tech-card h3{font-size:19px}.tech-card p{font-size:13px}.inside{padding-top:42px;padding-bottom:42px}.inside-grid,.connected-grid{grid-template-columns:1fr;gap:22px}.connected{padding-top:42px;padding-bottom:42px}.footer{padding:30px 16px}.footer-top{grid-template-columns:1fr 1fr}.footer-bottom{display:block}.footer-bottom a{display:inline-block;margin-right:20px}}
@media(max-width:540px){.utility a{width:45px}.utility .globe{display:grid}.hero-description{margin-top:56px}.recommend-card img{width:92px}.technology-grid{grid-template-columns:1fr}.tech-card{min-height:150px}.footer-top{grid-template-columns:1fr}.footer h3{border-bottom:1px solid var(--rule);padding-bottom:12px;margin:0 0 12px}}
</style></head><body>
<header class="header"><button class="mobile-menu-button" type="button" aria-label="Open navigation menu" aria-expanded="false" aria-controls="mobile-menu"><svg viewBox="0 0 24 24"><path d="M4 7h16M4 12h16M4 17h16"/></svg></button><a class="brand" href="https://www.ibm.com/" aria-label="IBM"><span class="ibm-mark">IBM</span></a><nav class="nav" aria-label="Primary"><a href="https://www.ibm.com/ca-en/products">Software <i class="chevron"></i></a><a href="https://www.ibm.com/ca-en/infrastructure">Infrastructure <i class="chevron"></i></a><a href="https://www.ibm.com/ca-en/consulting">Consulting</a><a href="https://www.ibm.com/ca-en/support">Support <i class="chevron"></i></a><a href="https://www.ibm.com/ca-en/think">Think</a></nav><div class="utility"><a href="https://www.ibm.com/ca-en/search" aria-label="Search"><svg viewBox="0 0 24 24"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg></a><a class="contact" href="https://www.ibm.com/ca-en/contact" aria-label="Contact"><svg viewBox="0 0 24 24"><path d="M4 5h16v12H8l-4 3z"/></svg></a><a class="globe" href="https://www.ibm.com/ca-en" aria-label="Region"><svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c-5 5-5 13 0 18M12 3c5 5 5 13 0 18"/></svg></a><a href="https://www.ibm.com/account/" aria-label="Account"><svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="3"/><path d="M5 21v-3a7 7 0 0 1 14 0v3"/></svg></a></div></header>
<nav class="mobile-menu" id="mobile-menu" aria-label="Mobile navigation"><div data-menu-main><button type="button" data-open-software>Software <span>›</span></button><a href="https://www.ibm.com/ca-en/infrastructure">Infrastructure <span>›</span></a><a href="https://www.ibm.com/ca-en/consulting">Consulting</a><a href="https://www.ibm.com/ca-en/support">Support <span>›</span></a><a href="https://www.ibm.com/ca-en/think">Think</a></div><div data-menu-software hidden><button class="back" type="button" data-back>‹ Back</button><strong>Software</strong><a href="https://www.ibm.com/ca-en/artificial-intelligence">Artificial intelligence <span>›</span></a><a href="https://www.ibm.com/ca-en/analytics">Data &amp; analytics <span>›</span></a><a href="https://www.ibm.com/ca-en/devops">DevOps <span>›</span></a><a href="https://www.ibm.com/ca-en/integration">Integration <span>›</span></a><a href="https://www.ibm.com/ca-en/security">Security <span>›</span></a><a href="https://www.ibm.com/ca-en/technology-business-management">Technology business management <span>›</span></a><a href="https://www.ibm.com/ca-en/products">Explore all products <span>→</span></a></div></nav>
<main><section class="hero"><div class="hero-copy"><h1>Scale AI through governance</h1><p class="hero-description">AI transformation requires more than deploying agents. Discover how leading enterprises scale Agentforce through unified data, governed systems and integrated architecture in the <em>State of Salesforce 2026-2027 report</em>.</p><div class="hero-actions"><a class="action primary" href="https://www.ibm.com/fr-fr/reports/state-of-salesforce?lnk=hpls1caen"><span>Download the full report</span><span>→</span></a><a class="action secondary" href="https://www.ibm.com/consulting/salesforce?lnk=hpls2caen"><span>Drive smarter transformation</span><span>→</span></a></div></div><img class="hero-visual" src="@@HERO@@" alt="Purple wave of bundled strands connects blue cables"><aside class="news"><h2>Latest News</h2><a href="https://canada.newsroom.ibm.com/2026-27-08-IBM-Study-Canadian-Sports-Fans-Expect-More-From-the-Fan-Experience-as-AI-Reshapes-Sports">IBM Study: Canadian Sports Fans Expect More From the Fan Experience as AI Reshapes Sports<span>→</span></a><a href="https://canada.newsroom.ibm.com/2026-07-29-IBM-Report-Canadas-Data-Breach-Costs-Hit-Record-High-as-Attacks-Target-Critical-Infrastructure">IBM Report: Canada's Data Breach Costs Hit Record High as Attacks Target Critical Infrastructure<span>→</span></a><div class="news-dots"><b>1</b><span>2</span><span>3</span><span>4</span></div></aside></section>
<section class="recommend"><h2 class="eyebrow">Recommended for you</h2><div class="recommend-grid"><a class="recommend-card" href="https://www.ibm.com/ca-en/events/ibm-at-all-in-montreal"><img src="@@MONTREAL@@" alt="Geometric blue and purple event pattern"><span class="copy"><small>ALL IN Montreal</small><strong>Join IBM at Canada's largest AI and tech event</strong></span></a><a class="recommend-card" href="https://bob.ibm.com/trial"><img src="@@BOB@@" alt="IBM Bob icon"><span class="copy"><small>Free trial</small><strong>Experience the full power of IBM Bob: Get 50 Bobcoins for 30 days</strong></span></a><a class="recommend-card" href="https://www.ibm.com/think/news/how-to-manage-AI-agents"><img src="@@AIAGENTS@@" alt="Blue abstract AI lines"><span class="copy"><small>News</small><strong>Explore why AI agents need stronger governance, oversight and accountability as they scale</strong></span></a><a class="recommend-card" href="https://www.ibm.com/new/announcements/manage-ai-data-risk-with-ibm-guardium-exposure-manager"><img src="@@SECURITY@@" alt="Green padlock illustration"><span class="copy"><small>News</small><strong>Learn why AI security starts with protecting data, not just models</strong></span></a></div></section>
<section class="impact"><h2 class="section-title">Smarter impact powered by IBM</h2><div class="impact-grid"><a class="impact-card" href="https://www.ibm.com/case-studies/innovmarine"><img src="@@SHIP@@" alt="Cargo ship"><span class="main">InnovMarine accelerates complex qualification work with AI driven automation</span><span class="metric"><b>~50–70%</b>cost reduction</span></a><a class="impact-card" href="https://www.ibm.com/case-studies/blue-pearl-bob"><img src="@@BLUEPEARL@@" alt="Blue Pearl logo"><span class="main">Explore how Blue Pearl turned weeks of work into days with IBM Bob</span><span class="metric"><b>~90%</b>faster delivery, completing a full Java uplift in ~3 days</span></a><a class="impact-card" href="https://www.ibm.com/case-studies/riverty"><img src="@@RIVERTY@@" alt="Riverty logo"><span class="main">See how Riverty speeds development with built-in security from IBM Vault</span><span class="metric"><b>10×</b>faster infrastructure deployment: from days to hours</span></a><a class="impact-card" href="https://www.ibm.com/case-studies/ibm-client-zero"><img src="@@IBMLOGOIMG@@" alt="IBM logo"><span class="main">Learn how IBM scaled AI-powered productivity with IBM watsonx Orchestrate</span><span class="metric"><b>USD 4.5 billion</b>productivity gains unlocked over three years</span></a></div></section>
<section class="technology"><h2 class="section-title">Top enterprise technology</h2><p class="intro">Recognized among <a href="https://www.ibm.com/new/announcements/clients-rank-ibm-among-top-enterprise-software-providers-in-2026-g2-best-software-awards">Top Enterprise Software Providers</a> in 2026 G2 Best Software Awards, IBM advances smarter business transformation through industry-leading AI, hybrid cloud, automation and data solutions.</p><div class="technology-grid"><a class="tech-card" href="https://bob.ibm.com/"><h3>IBM Bob™</h3><p>“We achieved 100% refactored code. Everything I thought would be a problem, Bob solved.”—APIS IT</p><span class="arrow">↗</span></a><a class="tech-card" href="https://www.ibm.com/products/watsonx-orchestrate"><h3>IBM watsonx Orchestrate®</h3><p>watsonx Orchestrate powers AI agents that cut HR costs by 40% and resolve 94% of employee requests automatically</p><span class="arrow">↗</span></a><a class="tech-card" href="https://www.ibm.com/products/confluent"><h3>IBM Confluent</h3><p>“Since we built Horus on top of Confluent, we’ve been able to save over a million dollars from what we were paying other vendors for.”—SecurityScorecard</p><span class="arrow">↗</span></a><a class="tech-card" href="https://www.ibm.com/products/flashsystem"><h3>IBM FlashSystem®</h3><p>Run smarter storage: zero downtime, AI optimization and at least 40% lower costs with FlashSystem</p><span class="arrow">↗</span></a><a class="tech-card" href="https://www.hashicorp.com/en/products/vault"><h3>IBM Vault®</h3><p>“Vault has ... lowered how much effort it takes to meet regulatory compliance goals and reduced our risk of both a breach and unplanned downtime.”—NORD/LB</p><span class="arrow">↗</span></a><a class="tech-card" href="https://www.ibm.com/products/maximo"><h3>IBM Maximo®</h3><p>Reduce unplanned downtime by 47% and extend asset lifespan by 17% with IBM Maximo</p><span class="arrow">↗</span></a><a class="tech-card" href="https://www.ibm.com/products/planning-analytics"><h3>IBM Planning Analytics</h3><p>Volkswagen Group Services reduced monthly reporting time from 7 days to just seconds and increased HR productivity by 85% with Planning Analytics</p><span class="arrow">↗</span></a><a class="tech-card" href="https://www.ibm.com/consulting"><h3>IBM Consulting®</h3><p>Partner with 150,000+ experts in IBM Consulting, the only global consultancy within a major technology company</p><span class="arrow">↗</span></a></div></section>
<section class="inside"><h2 class="section-title">Inside IBM</h2><div class="inside-grid"><div><h3>Our company</h3><p>Explore IBM history and culture of putting technology to work in the real world.</p><a href="https://www.ibm.com/ca-en/about">About IBM →</a><a href="https://www.ibm.com/history">Our history →</a></div><div><h3>Our innovations</h3><p>Visit the IBM lab and see what's in store for the future of computing.</p><a href="https://research.ibm.com/">IBM Research® →</a><a href="https://www.ibm.com/quantum">Quantum computing →</a></div><div><h3>Our people</h3><p>See what it takes to become an IBMer or build your skills with our educational courses.</p><a href="https://www.ibm.com/careers">Become an IBMer →</a><a href="https://skillsbuild.org/">Start learning →</a></div></div></section>
<section class="connected"><h2 class="section-title">Stay connected</h2><div class="connected-grid"><img src="@@CONNECTED@@" alt="IBM team engaging attendees at an event"><div class="newsletter"><h3>What's New at IBM newsletter subscription</h3><p>Get updates from IBM. Your subscription will be delivered in English.</p><form id="ibm-newsletter"><label>First name*<input name="first-name" autocomplete="given-name"></label><label>Last name*<input name="last-name" autocomplete="family-name"></label><label>Business email*<input name="email" type="email" autocomplete="email"></label><button type="submit">Subscribe</button></form></div></div></section></main>
<footer class="footer"><div class="footer-top"><div><h3>Discover</h3><a href="https://www.ibm.com/products">Products</a><a href="https://www.ibm.com/consulting">Consulting services</a><a href="https://www.ibm.com/industries/en-us/">Industries</a><a href="https://www.ibm.com/case-studies">Case studies</a><a href="https://research.ibm.com/">Research</a></div><div><h3>Follow</h3><a href="https://www.linkedin.com/company/ibm">LinkedIn</a><a href="https://x.com/IBM">X</a><a href="https://www.instagram.com/ibm/">Instagram</a><a href="https://www.youtube.com/@IBM">YouTube</a><a href="https://www.ibm.com/ca-en/think/podcasts">Podcasts</a></div><div><h3>Connect</h3><a href="https://www.ibm.com/partnerplus/directory/companies">Business Partners</a><a href="https://www.ibm.com/docs/en">Documentation</a><a href="https://www.ibm.com/events">Events</a><a href="https://www.ibm.com/subscribe/">Newsletters</a><a href="https://www.ibm.com/mysupport/s/">Support</a></div><div><h3>About</h3><a href="https://www.ibm.com/ca-en/about">Overview</a><a href="https://www.ibm.com/careers">Careers</a><a href="https://www.ibm.com/investor">Investor relations</a><a href="https://canada.newsroom.ibm.com/">Newsroom</a><a href="https://www.ibm.com/ca-en/trust">Security, privacy and trust</a></div></div><div class="footer-bottom"><a href="https://www.ibm.com/ca-en/contact">Contact IBM</a><a href="https://www.ibm.com/privacy">Privacy</a><a href="https://www.ibm.com/ca-en/legal">Terms of use</a><a href="https://www.ibm.com/accessibility/ca/en/">Accessibility</a></div></footer>
<script>(()=>{const button=document.querySelector('.mobile-menu-button'),menu=document.getElementById('mobile-menu'),main=menu.querySelector('[data-menu-main]'),software=menu.querySelector('[data-menu-software]');button.addEventListener('click',()=>{const open=!menu.classList.contains('open');menu.classList.toggle('open',open);button.setAttribute('aria-expanded',String(open));button.setAttribute('aria-label',open?'Close navigation menu':'Open navigation menu');button.innerHTML=open?'×':'<svg viewBox="0 0 24 24"><path d="M4 7h16M4 12h16M4 17h16"/></svg>';main.hidden=false;software.hidden=true});menu.querySelector('[data-open-software]').addEventListener('click',()=>{main.hidden=true;software.hidden=false});menu.querySelector('[data-back]').addEventListener('click',()=>{main.hidden=false;software.hidden=true});document.getElementById('ibm-newsletter').addEventListener('submit',event=>{event.preventDefault();location.assign('https://www.ibm.com/subscribe/')})})();</script>
</body></html>'''
    replacements = {
        '@@HERO@@': image('The%20State%20of%20Salesforce'),
        '@@MONTREAL@@': image('r4u-quantum'),
        '@@BOB@@': image('ibm-bob-homepage'),
        '@@AIAGENTS@@': image('ApplyingAI-Security'),
        '@@SECURITY@@': image('illustration-flat-style-kit'),
        '@@SHIP@@': image('this-week-at-ibm'),
        '@@BLUEPEARL@@': image('blue-pearl'),
        '@@RIVERTY@@': image('riverty-logo'),
        '@@IBMLOGOIMG@@': image('ibm-logo-2x1'),
        '@@CONNECTED@@': image('stay-connected'),
    }
    for token, path in replacements.items():
        html = html.replace(token, path)
    if '@@' in html:
        raise ValueError('Unresolved image placeholder')
    (ROOT / 'ibm.html').write_text(html)
    print(f'Wrote ibm.html using {len(replacements)} observed IBM images')


if __name__ == '__main__':
    main()
