import fs from 'node:fs';
import path from 'node:path';
import {JSDOM, VirtualConsole} from 'jsdom';

const work = path.resolve('.stitch-work/current-official');
for (const brand of ['figma', 'framer']) {
  const reference = JSON.parse(fs.readFileSync(path.join(work, brand + '-desktop-browser-reference.json')));
  const mobile = JSON.parse(fs.readFileSync(path.join(work, brand + '-mobile-browser-reference.json')));
  const document = new JSDOM(reference.htmlParts.join(''), {virtualConsole: new VirtualConsole()}).window.document;
  document.querySelectorAll('style,script').forEach(e => e.remove());
  const brief = brand === 'figma'
    ? `Reconstruct the actual public Figma homepage captured on October 10, 2026, at 1280×720. Keep its white canvas, original multicolor Figma symbol, black figmaSans typography, 80px desktop navigation, Products/Solutions/Community/Resources/Pricing controls, Log in, outlined Contact sales, and black Get started for free action. The hero is not a centered SaaS dashboard: a narrow left headline column reads “The full-stack creative canvas”, with four lines at this width, x40/y396, width288, height224, 56px/56px, weight400, -1.25px tracking. The tall original Vimeo product montage is in the middle; the separate black Get started action sits to the right. Use the actual public player source recorded below, with the original source crop and proportions. Do not replace the video with invented product cards, a blank placeholder, or generic AI artwork. The source player genuinely loaded and played in the browser; a blob URL from inside it is not a reusable media URL. Preserve the current Config India announcement and Register destination in their actual captured position. Below the hero, preserve “Move fast in the right direction on an AI-native canvas.”, the original collaborator section, “One workspace for your entire product development process.”, all current product sections, customer evidence, the closing action and complete footer. Use the actual captured text and source images. The compact 390px version has the 36px/36px heading at x16/y118, width358 and height72, original mobile video composition, menu and product submenu. Do not force the desktop hero arrangement onto mobile.`
    : `Reconstruct the actual current Framer public homepage at 1280×720. It is a black page with white GT Walsheim Medium headings and Inter Variable interface type. The original Framer mark and wordmark sit at x40; keep Platform/Solutions/Resources menus, Enterprise, Pricing, Log in and the white Sign up action in the 64px navigation. The left-aligned hero reads exactly “Framer is the design agent for every step from idea to launch”, x40/y164, width721, height108, 54px/54px, weight500, -2.16px tracking. Preserve Get started for free, the platform-specific Download app destination, and the right-aligned “New: Skills” link. The original rounded video starts x40/y372 at1200×673.4453125; keep the actual MP4 and poster URLs recorded below, its source crop, and the 0:36 control. Do not invent an agent dashboard or substitute a still illustration for this real video. Continue with “Agents that work alongside you, not instead of you”, the three Design/CMS/Code agent sections and their current public demonstrations, “Not just vibes, a full platform”, “Shipped with Framer”, “Trusted by teams shipping big sites”, “Built on a community that isn’t going anywhere”, “Your next idea starts here”, and the current full footer. Preserve all current source copy, original customer artwork and the actual navigation states. At390px use the source 36px/36px hero at x20/y124, width350, height108, -1.44px tracking; the hero video is edge-to-edge390×218.8671875 at y365.6015625. Keep the compact top bar and genuine full-screen mobile menu/platform submenu. The source has different desktop and mobile demonstrations: preserve those differences.`;
  const players = brand === 'figma' ? JSON.parse(fs.readFileSync(path.join(work, 'figma-vimeo-browser-reference.json'))).references : null;
  const prompt = `Build a complete desktop screen and HTML for a free, attributed study of this dated official homepage. These implementation instructions were independently written from current public browser observations. Do not reuse an old project screen or an upstream AI prompt. The current reference takes priority over previous generations.\n\n${brief}\n\nUse the original public logos, fonts, images and media; retain the measured geometry, typography, section order, links and observed responsive states. Account actions must open the genuine official service. This study must not collect credentials, contain checkout or charge visitors. Do not fabricate content, metrics, navigation entries or artwork. A successful generation is not visual acceptance.\n\nOfficial reference: ${reference.reference_url}\nObserved: ${reference.observed_at}\nDesktop viewport:1280×720. Narrow viewport:390×844 with desktop user agent; this is not a true phone test.\n\nDesktop heading measurements:\n${JSON.stringify(reference.headings.filter(h => h.text && h.box.height > 1), null, 2)}\n\nNarrow heading measurements:\n${JSON.stringify(mobile.headings.filter(h => h.text && h.box.height > 1).slice(0,12), null, 2)}\n\nObserved public images:\n${JSON.stringify(reference.images.filter(i => !i.src.startsWith('data:')).map(i => ({url:i.src, alt:i.alt, box:i.box})), null, 2)}\n\nObserved native video sources and boxes:\n${JSON.stringify(reference.videos, null, 2)}\n\nObserved original Figma Vimeo components (when applicable):\n${JSON.stringify(players, null, 2)}\n\nCurrent ordered page copy (may include alternate navigation/animation states):\n${document.body.textContent.replace(/\s+/g, ' ').trim()}\n`;
  fs.writeFileSync(path.join(work, brand + '-stitch-oct10-desktop-prompt.md'), prompt);
  console.log(JSON.stringify({brand, promptChars: prompt.length}));
}
