import fs from 'node:fs';
import path from 'node:path';
import {JSDOM,VirtualConsole} from 'jsdom';
const work=path.resolve('.stitch-work/current-official');
for(const brand of ['claude','notion']) {
  const reference=JSON.parse(fs.readFileSync(path.join(work,brand+'-desktop-browser-reference.json')));
  const mobile=JSON.parse(fs.readFileSync(path.join(work,brand+'-mobile-browser-reference.json')));
  const document=new JSDOM(reference.htmlParts.join(''),{virtualConsole:new VirtualConsole()}).window.document;
  document.querySelectorAll('style,script,[id^="onetrust"],[id^="ot-sdk"]').forEach(e=>e.remove());
  const geometry=reference.headings.filter(h=>h.text && h.box.height>0).map(h=>({text:h.text,box:h.box,font:h.font}));
  const mobileGeometry=mobile.headings.filter(h=>h.text && h.box.height>0).slice(0,8);
  const brief=brand==='claude'
    ? 'Rebuild the captured official /index.html homepage at 1280×720. It is a dark page with warm white Anthropic Serif headings, Anthropic Sans interface text and the original copper Claude mark. Preserve the 85px header, the source navigation and the two-column hero. The left column says “Think fast, built faster” exactly, including the observed word built. The smaller line is “Brainstorm in Claude, build in Cowork”. Retain the original Google sign-in mark, outlined Google action, white email action, privacy copy and Download Claude action. The right side is a rounded 564.5703125px square starting at x656/y190.7109375. The live source video has an empty src and readyState 0: retain its observed dark skeleton, never invent a Cowork task list, screenshot or replacement animation. Below are Explore plans with Individual and Team & Enterprise tabs, the exact observed Free/Pro/Max and Team/Enterprise/Education content, FAQ, customer evidence and the complete current multi-column footer. The root URL redirected to login in this browser; /index.html is the actual public marketing reference, not a private account. Preserve the captured narrow layout without calling a desktop user agent a real phone test.'
    : 'Rebuild the current Notion public homepage at 1280×720. Use the white canvas, original black cube logo and NotionInter. Keep the 64px navigation, Product/Resources menus, Pricing, Request a demo, Log in and blue Get Notion free button. The centered hero h1 starts at x64/y144, width1152, with 96px font, 100px line height, weight600 and -4.6px tracking. Its wording is “Where teams and agents Think together.” with the original colored rounded Think pill; observed timed variants also included Build, Jam and Scale. Preserve that source composition rather than a generic dashboard hero. Keep the exact subtitle and two centered actions. The original 2560:1600 product video renders x161/y533.6171875 at958×598.75; use the observed original video URL and existing source poster/illustration. Preserve the customer-logo marquee, AI where your team works, Capture knowledge, Find answers, Automate busywork, the five actual use cases, Cursor/Faire/Ramp stories, original evidence, closing action and footer. Do not fabricate AI-agent metrics or substitute generic artwork. At390px use the actual compact header and the source42px/48px hero, -1.5px tracking, width358 and height144.609375. The source hides the large hero video at this width.';
  const prompt=`Create a faithful desktop screen and complete HTML for a free, attributed design study. These AI implementation instructions are newly authored from dated public browser measurements; no upstream prompt is reused. The current observed official page takes precedence over any old generated screen.\n\n${brief}\n\nUse original public font, image and vector sources. Preserve exact text, section order, geometry and crop. All account actions must go to the genuine official service; this study must not collect credentials. Generation success is not visual acceptance.\n\nReference: ${reference.reference_url}\nObserved: ${reference.observed_at}\nDesktop viewport:1280×720\nNarrow viewport:390×844 with desktop user agent.\n\nDesktop heading measurements:\n${JSON.stringify(geometry,null,2)}\n\nNarrow heading measurements:\n${JSON.stringify(mobileGeometry,null,2)}\n\nObserved images:\n${JSON.stringify(reference.images.map(i=>({url:i.src,alt:i.alt,box:i.box})),null,2)}\n\nObserved videos:\n${JSON.stringify(reference.videos,null,2)}\n\nCurrent ordered page copy (includes hidden navigation and alternate plan content):\n${document.body.textContent.replace(/\s+/g,' ').trim()}\n`;
  fs.writeFileSync(path.join(work,brand+'-stitch-oct10-desktop-prompt.md'),prompt);
  console.log(JSON.stringify({brand,promptChars:prompt.length}));
}
