import fs from 'node:fs';
import path from 'node:path';
import { JSDOM, VirtualConsole } from 'jsdom';

const root = path.resolve('.stitch-work/current-official');
for (const brand of ['spotify', 'linear']) {
  const reference = JSON.parse(fs.readFileSync(path.join(root, `${brand}-desktop-browser-reference.json`)));
  const provenance = JSON.parse(fs.readFileSync(path.join(root, `${brand}-browser-asset-provenance.json`)));
  const document = new JSDOM(reference.htmlParts.join(''), { virtualConsole: new VirtualConsole() }).window.document;
  document.querySelectorAll('style,[id^="onetrust"],[id^="ot-sdk"]').forEach(node => node.remove());
  const text = document.body.textContent.replace(/\s+/g, ' ').trim();
  const grids = [...document.querySelectorAll('[role="grid"]')].map(grid => ({
    label: grid.getAttribute('aria-label') || document.getElementById(grid.getAttribute('aria-labelledby'))?.textContent || '',
    rows: [...grid.querySelectorAll('[role="row"]')].map(row => ({
      text: row.textContent.replace(/\s+/g, ' ').trim(),
      image: row.querySelector('img')?.getAttribute('src'),
      links: [...row.querySelectorAll('a[href]')].map(link => ({ text: link.textContent.trim(), href: new URL(link.getAttribute('href'), reference.reference_url).href })),
    })),
  })).filter(grid => grid.rows.length && grid.label.trim() !== 'Your Library');
  const geometry = reference.headings.filter(heading => heading.box.height > 0).map(heading => ({ text: heading.text, box: heading.box, font: heading.font }));
  const fonts = provenance.assets.filter(asset => asset.kind === 'font' && (brand !== 'spotify' || asset.source_url.includes('SpotifyMix'))).map(asset => ({ url: asset.source_url, sha256: asset.sha256 }));
  const images = reference.images.slice(0, brand === 'spotify' ? 12 : undefined).map(image => ({ url: image.src, alt: image.alt, box: image.box }));
  const brief = brand === 'spotify'
    ? 'Reconstruct the signed-out Taiwan web player at1280×720. Use a64px global navigation, a320px library panel atx8/y64, and an independently scrolling main panel atx336/y64 with height574 and width896. The background is black, panels are near#121212, the top of the main panel has the observed restrained dark gradient. Cover tiles are154px square in the first desktop row, followed by round artist portraits. Keep the54-to56-card source update exactly as supplied by the current grids below; derive the current count from these rows rather than reusing the old export. Use SpotifyMixUI for UI text and SpotifyMixUITitle for24px/700 section headings. Keep the white Log in and Sign up free pills, the exact native SVG marks, and the fixed purple-to-blue preview strip atx8/y646, width1264, height66. The five content groups are Trending songs, Popular artists, Popular albums and singles, Popular radio and Featured Charts. Preserve independent vertical scrolling and horizontal rows; the screenshot does not represent a long outer-document marketing page. The existing desktop browser at390px clips an812px-wide desktop player: that observation is not evidence of a mobile app layout. Do not invent a phone navigation bar or claim true-mobile fidelity.'
    : 'Reconstruct the actual current Linear homepage at1280×720. Use the near-black#08090a canvas and Inter Variable throughout, with Berkeley Mono in the code/demo details. The navigation is72px tall and the hero starts with generous empty space. Place the headline atx40/y272, width1198, height128, in64px/64px, weight510, letter spacing-1.408px; it reads The product development system for teams and agents. The subtitle is Purpose-built for planning and building products. Designed for the AI era. Keep New Loops at the right of this intro row and the original layered app demo beginning aroundy550. The demo is DRV-8852 Faster app launch, with Linear sidebar, actual issue, activity, properties and code content. Preserve customer vector logos and the source section order: introduction, Intake and integrations, Planning and monitoring, AI and automations, Build review and ship, Changelog, customer quotations, closing action and five-column footer. The current Changelog starts with Stacked pull requests datedOct8,2026; use the supplied source text instead of older or fictional release entries. In the responsive390×844 reference the hero uses38px/41.8px, weight510, letter spacing-0.836px, atx23/y196, width343 and height167.1875, with a compact navigation and original scaled app demo. Do not replace the software panels with generic gradient illustrations or add invented numerical metrics.';
  const prompt = `Build a faithful, source-measured reconstruction for a free design study. These implementation instructions are independently written for this task. The previous generated screen is only historical context; the dated public reference below is the authority for this revision.\n\n${brief}\n\nUse the actual source fonts, image URLs and public vector marks. Preserve wording, order, crop, alignment and spacing from the observations. Keep account actions directed to the real official service; the study must not collect credentials. Retain real links. Do not treat generated output as visually accepted merely because generation succeeded. Return a desktop screen and its complete HTML.\n\nReference: ${reference.reference_url}\nObserved: ${reference.observed_at}\nViewport:1280×720\n\nMeasured heading typography and rectangles:\n${JSON.stringify(geometry, null, 2)}\n\nOriginal font sources and byte fingerprints:\n${JSON.stringify(fonts, null, 2)}\n\nObserved image URLs and rectangles:\n${JSON.stringify(images, null, 2)}\n\nCurrent ordered card grids (if present):\n${JSON.stringify(grids, null, 2)}\n\nObserved public page copy and demo labels:\n${text}\n`;
  const corrected = prompt.replace('Keep the54-to56-card source update exactly as supplied by the current grids below; derive the current count from these rows rather than reusing the old export.', 'Keep all 54 current content cards in the five ordered grids below; their text, covers and destinations are current source data, not the old recommendation list.');
  fs.writeFileSync(path.join(root, `${brand}-stitch-oct10-desktop-prompt.md`), corrected);
  console.log(JSON.stringify({ brand, promptChars: corrected.length, grids: grids.map(grid => ({ label: grid.label, rows: grid.rows.length })) }));
}
